// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: shorturl.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Url struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	IsPublic      bool                   `protobuf:"varint,3,opt,name=isPublic,proto3" json:"isPublic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Url) Reset() {
	*x = Url{}
	mi := &file_shorturl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{0}
}

func (x *Url) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Url) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Url) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type ShortKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	IsPublic      bool                   `protobuf:"varint,3,opt,name=isPublic,proto3" json:"isPublic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortKey) Reset() {
	*x = ShortKey{}
	mi := &file_shorturl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortKey) ProtoMessage() {}

func (x *ShortKey) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortKey.ProtoReflect.Descriptor instead.
func (*ShortKey) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{1}
}

func (x *ShortKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ShortKey) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ShortKey) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

var File_shorturl_proto protoreflect.FileDescriptor

const file_shorturl_proto_rawDesc = "" +
	"\n" +
	"\x0eshorturl.proto\x12\bshorturl\"K\n" +
	"\x03Url\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x03R\x06userID\x12\x1a\n" +
	"\bisPublic\x18\x03 \x01(\bR\bisPublic\"P\n" +
	"\bShortKey\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x03R\x06userID\x12\x1a\n" +
	"\bisPublic\x18\x03 \x01(\bR\bisPublic2l\n" +
	"\bShortUrl\x12+\n" +
	"\vGetShortUrl\x12\r.shorturl.Url\x1a\r.shorturl.Url\x123\n" +
	"\x0eGetOriginalUrl\x12\x12.shorturl.ShortKey\x1a\r.shorturl.UrlB\"Z mediahub/services/shorturl/protob\x06proto3"

var (
	file_shorturl_proto_rawDescOnce sync.Once
	file_shorturl_proto_rawDescData []byte
)

func file_shorturl_proto_rawDescGZIP() []byte {
	file_shorturl_proto_rawDescOnce.Do(func() {
		file_shorturl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shorturl_proto_rawDesc), len(file_shorturl_proto_rawDesc)))
	})
	return file_shorturl_proto_rawDescData
}

var file_shorturl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shorturl_proto_goTypes = []any{
	(*Url)(nil),      // 0: shorturl.Url
	(*ShortKey)(nil), // 1: shorturl.ShortKey
}
var file_shorturl_proto_depIdxs = []int32{
	0, // 0: shorturl.ShortUrl.GetShortUrl:input_type -> shorturl.Url
	1, // 1: shorturl.ShortUrl.GetOriginalUrl:input_type -> shorturl.ShortKey
	0, // 2: shorturl.ShortUrl.GetShortUrl:output_type -> shorturl.Url
	0, // 3: shorturl.ShortUrl.GetOriginalUrl:output_type -> shorturl.Url
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shorturl_proto_init() }
func file_shorturl_proto_init() {
	if File_shorturl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shorturl_proto_rawDesc), len(file_shorturl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shorturl_proto_goTypes,
		DependencyIndexes: file_shorturl_proto_depIdxs,
		MessageInfos:      file_shorturl_proto_msgTypes,
	}.Build()
	File_shorturl_proto = out.File
	file_shorturl_proto_goTypes = nil
	file_shorturl_proto_depIdxs = nil
}
